### ISSUE TITLE
Add explicit depencency to lodash in package.json

### ISSUE THREAD

**Issue by michaelschnyder** [hatchteam/twigs#37]
Any good reason, why is this not done? If i install a module, I would expect to have all transient dependencies installed automatically.

It looks like that twigs requires even an older version of lodash 3.x? than available

**Comment by xeronimus** [comment]
1. This just might be missing in package.json. ( by mistake )
2. lodash 4 is quite young and removed some of the features (e.g. "pluck") -> check if we can update (3.x is still stable, not deprecated..)

**Comment by michaelschnyder** [comment]
i tried to update to version 4.3.0 but it seems that they introduced changes which caused the twigs-library to work unexpected (no menu)

But you are right, i was the permission evaluator which caused the error, sry.

**Comment by xeronimus** [comment]
jetpack has a dependency to  "lodash": "2.4.1" ... from 2.x to 4.x  is a big jump ;-)
